name: Build and Deploy Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Linux
      run:  |
        cd ./Blipper
        dotnet publish -c Release --self-contained true --runtime linux-x64 --framework net5.0 /p:useapphost=true
    - name: Copy Files to Develop
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./Blipper/Blipper/bin/Release/net5.0/linux-x64/publish/*
        remote_path: /home/deploy/blipper/master/staging
        remote_host: ${{ secrets.DEPLOY_SERVER }}
        remote_user: deploy
        remote_port: 22509
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Call deploy.sh on Server
      uses: appleboy/ssh-action@master
      with:
        host: mdosupply.hosting.olivetree.cloud
        port: 22509
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: "sudo /var/aspnetcore/blipper/master/deploy.sh"
